#
# Copyright 2016, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

#This library uses a rust cargo project to generate it's lib*.a file
RUST_TARGET := libcompiler-rt.a

export RUST_SRC := $(HOME)/.xargo/src

include $(SEL4_COMMON)/common.mk
